[env]
TERM =  'xterm-256color'
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
  # background opacity
opacity = 1.0
dynamic_title = true

[scrolling]
history = 10000

[font]
normal = { family = "VictorMono Nerd Font", style = "Bold" }
italic = { family = "VictorMono Nerd Font", style = "Italic" }
size = 16
