icons_format = "{icon}"

[theme]
theme = "plain"
[theme.overrides]
idle_bg = "#282828"
idle_fg = "#ebdbb2"
info_bg = "#458588"
info_fg = "#ebdbb2"
good_bg = "#98971a"
good_fg = "#ebdbb2"
warning_bg = "#d79921"
warning_fg = "#ebdbb2"
critical_bg = "#cc241d"
critical_fg = "#ebdbb2"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"

[icons]
icons = "none"

[[block]]
block = "custom"
command = "echo -n '󱑎  '&& date +%Y-%m-%d\\ %H:%M"
interval = 1

[[block]]
block = "cpu"
[block.icons_overrides]
cpu = " "

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
#format_alt = " $icon_swap $swap_used_percents.eng(w:2) "
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95
[block.icons_overrides]
memory_mem = ""

# [[block]] 
# block = "bluetooth"
# mac = ""
# format = " $icon "
# [block.battery_state]
# "0..20" = "critical"
# "21..70" = "warning"
# "71..100" = "good"
# [block.icons_overrides]
# headphones = "󰋋"
# joystick = ""
# keyboard = "󰥻"
# mouse = "󰍽"
# bluetooth = "󰂯"
# [[block.click]]
# button = "left"
# cmd = "blueman-manager"

[[block]]
block = "sound"
driver = "pulseaudio"
[[block.click]]
button = "left"
cmd = "pavucontrol"
[block.icons_overrides]
microphone_muted = ""
microphone = "󰍬"
volume_muted = "󰸈"
volume = "󰕾"
headphones = "󰋋"

[[block]]
block = "net"
interval = 1
[block.icons_overrides]
net_loopback = "󰈀"
net_vpn = "󰖂"
net_wired = "󰈀"
net_wireless = "󰖩 "
net_up = ""
net_down = ""
[[block.click]]
button = "left"
cmd = "alacritty -e nmtui-connect"

#[[block]]
#block = "external_ip"
#format = " $ip $country_code "
